# Runs npm test when a PR is created or a PR attempts to merge with main
name: Node.js CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [18.x]

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm ci
            - run: npm install @babel/core @babel/preset-env # Install Babel dependencies
            - run: npx babel src --out-dir dist # Build your files with Babel
            - run: npm test
